---
name: PART3 - CH4 - AWS OIDC Credentials 
on: workflow_dispatch
jobs:
  s3:
    name: S3 Upload using OIDC Credentials
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Generate File
      run: |
        echo "Build ID: ${{ github.run_id }} | auth through AWS OIDC" > ./build.txt
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        role-duration-seconds: 900
    - name: Upload File to AWS S3
      run: |
        aws s3 cp build.txt s3://githubaction-test-01/build.txt
    - name: Notice when a build finishes
      if: always()
      uses: 8398a7/action-slack@v3.2.0
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        status: ${{job.status}}
        fields: repo,message,workflow,job,ref
        author_name: Github Action Slack
