---
  name: PART3 - CH4 - AWS AccessKey Credentials 
  on: workflow_dispatch
  jobs:
    s3:
      name: S3 Upload using Access Key Credentials
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: read
      steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Generate File
        run: |
          echo "Build ID: ${{ github.run_id }}" auth through AWS Access Key > ./build.txt
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload File to AWS S3
        run: |
          aws s3 cp build.txt s3://githubaction-test-01/build.txt
      - name: Notice when a build finishes
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{job.status}}
          fields: repo,message,workflow,job,ref
          author_name: Github Action Slack
